### The Dos and the Don'ts {-}

#### Git Don'ts {-}

##### Version control sensitive data {-}

This is a security concern. Servers which host remote repositories are not necessarily as secure as the network the data are stored on. Additionally, storing the data in more than one location increases the likelyhood that a data breach could occur. 
 
##### Use git as a data versioning tool {-}

Git is not a data versioning tool. This book will discuss data versioning at a later point!
Storing data on the git (even unsensitive data) will clutter the repository’s history. 

An exception to this rule may be storing static metadata (e.g. config file) or fake data used for unit testing, along with some other well thought-out special cases. Think very carefully about whether there's a good reason to put data in the repository and seek guidance before doing so.
		
##### Version control binary files {-}

Any file that cannot be opened by a text editor (Notepad, Atom, Sublime, etc.). If you are unsure about whether a file is a binary file, just try to open it in Notepad—if you see a bunch of gibberish then it is! If you see a proper text representation of what you know the file contains, then it isn’t! 

Git is a version control tool, meaning that it tracks changes to the contents of a file. This works great for text files, but not at all for binary files. If you change a single character of a Word document, all of the contents of the binary file will change. This means that git will not be able to show you what changed about the file, only that the file changed.

Don't version these file types:

* Word documents (.doc, .docx)
* Excel files (.xls, .xslsx, .xlsm, .xlsb, ...)
* Images (.jpg, .png, ...) 
* Executables (.exe, .dll, ...)
* SAS/Stata/other data files (.sas7bdat, .dta, .dat (sometimes), ...) 

There can be exceptions, but generally it is bad practice to version control this type of file. They, like data, will bloat the repository for no good reason.
	
##### Version control temporary files {-}

Windows and other programs often create temporary files when a file is in the process of being written or when a team member has the file open. They often have weird names starting with "~$" or extensions like ".bak". Don't version control these as they are temporary!

5. Version control output files

This includes log files and other direct program output. Like binary files, these files are likely to change a lot when they change, but they are also conceptually more like data than they are like code.
	
6. Use name versioning for files tracked by git

Code should never be names _v1 or _v2_final or _v3_final_final_JH. Git takes care versioning for you! The days of archiving code and renaming different versions are over! Just make your change and commit it. Then, to access the previous version, just use `git checkout` or use `git diff` or `git show` to view changes.

#### Gits Dos {-}

##### Write concise and informative commit messages {-}

Commit messages are the easiest way for other collaborators and future versions of yourself to figure out what changes were made in each commit. This makes it easier to trace errors, keep track of features, and find explanations for changes. Remember the commit message should explain the why not the what.
	
##### Make each commit a single cohesive change {-}

Conceptually, each commit should be a single unit of work (e.g. "fixed bug X" or "added X section to report"" or "changed working in section X"). This unit of work could be small (a couple lines of code, or even fixing a typo) or it could be large (adding an entire section to a program), but all changes/additions/deletions within a commit should be related. A quick rule is that you should rarely need to use the word "and" in a commit message—if you are, then you should probably make that commit into two or more commits.

Doing this helps everyone get a better sense of what each commit changed, but also makes it easier to inspect and roll back changes. We wouldn’t want to have to undo a change unrelated to the one that actually needs to be reversed

When adding files to be committed, use `git add [file/s]` to add only certain modified files to staging. Use `git reset` to unstage all files if you accidentally add too many
	
##### Review all changes before committing {-}

This quick and simple step should make sure that you avoid all of the "do nots" above 99% of the time.

- First add the files you want to commit: `git add [files]` or `git add .` to stage all files for commit
- Review the changes: `git status` to see a list of all files that will be committed, and `git diff --cached` to see a detailed view of all changes to each staged file
- Commit! `git commit -m [my concise and informative commit message]`
		
##### Use a .gitignore file {-}

A .gitignore file that tells git which file types not to track. Git will ignore any files that match patterns specified in the .gitignore.
