## Resources

### General {-}

* [Advanced R](http://adv-r.had.co.nz/) - Hadley Wickham
* [Swirl Courses](http://swirlstats.com/scn/title.htmls)
* [Swirl Courses Git Repo](https://github.com/swirldev/swirl_courses)
* [Quick R](https://www.statmethods.net/) - Rob Kabacoff
* [R Studio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/) - Rstudio

#### Style Guides {-}

* [R Style Guide](http://adv-r.had.co.nz/Style.html) - Hadley Wickham
* [Google Style Guide](https://google.github.io/styleguide/Rguide.xml) - Google

### Data Management {-}

* [Data wrangling cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf) - Rstudio

* [Tidy Eval](https://tidyeval.tidyverse.org/sec-do-you-need.html) - Hadley Wickham and Lionel Henry

### Reproducibility {-}

* [Packaging data analytical work reproducibly
using R (and friends)](https://peerj.com/preprints/3192.pdf) - Marwick, Boettiger, Mullen

#### Package Development {-}

* [R Packages](http://r-pkgs.had.co.nz/) - Hadley Wickham
* [R extensions manual](https://cran.r-project.org/doc/manuals/R-exts.html#Creating-R-packages)
* [goodrpackages](https://masalmon.eu/2017/12/11/goodrpackages/) - Maelle Salmon
* [Remote packages](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html) - Hadley Wickham and Jim Hester

#### Environments {-}

* [Creating Reproducible Software Environments with Packrat](https://bconnelly.net/2014/07/creating-reproducible-software-environments-with-packrat/) - Brian Connelly

### Modeling {-}

#### Data Science {-}

* [R for Data Science](https://r4ds.had.co.nz/) - Hadley Wickham

### Visualization {-}

* [ggplot2](https://www.amazon.com/dp/0387981403/ref=cm_sw_su_dp?tag=ggplot2-20) - Hadley Wickham
* [R Graphics Cookbook](https://www.amazon.com/dp/1449316956/ref=cm_sw_su_dp?tag=ggplot2-20) - Winston Chang
* [ggplot2 cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf) - Rstudio

### Quality {-}

* [Ten Rules of Defensive Programming](https://www.r-bloggers.com/the-ten-rules-of-defensive-programming-in-r/)

#### Testing {-}

* [Getting Started with Testthat](https://journal.r-project.org/archive/2011/RJ-2011-002/RJ-2011-002.pdf) - Hadley Wickham
* [R packages](http://r-pkgs.had.co.nz/tests.html#test-workflow) - Hadley Wickham

### Command Line Interface {-}

* [Passing arguments to an R script from command lines](https://www.r-bloggers.com/passing-arguments-to-an-r-script-from-command-lines/)

### Efficiency {-}

#### Parallelization {-}

* [Quick Intro to Parallel Computing in R](https://nceas.github.io/oss-lessons/parallel-computing-in-r/parallel-computing-in-r.html) - Matt Jones
* [Multicode Data Science with R and Python](https://blog.dominodatalab.com/multicore-data-science-r-python/)
* [Beyond Single-Core R](https://ljdursi.github.io/beyond-single-core-R/#/16) - Jonathan Dursi

### Object-Oriented Programming

* [Object-Oriented Programming, Functional Programming and R](https://arxiv.org/pdf/1409.3531.pdf) - John M. Chambers