## Code Review

A code review is the chance to walk-through and explain your code line-by-line to others involved with the project. Code reviews provide opportunities for other programmers or researchers to help catch bugs and improve overall code quality.  
	
### Review participants {-}

* The original author(s) of the code being updated 
* At least one more senior or programmer of an equivalent level  
* People knowledgeable about the content area of your code
* At least one person who is very familiar the programming language
		
### General tips for success {-}

Before: 

* If there are data involved and you wish to run the code line-by-line, pre-load the data (or at least a sample of the data)
* Comment the code as this will make it easier to walk through or explain things on the spot
* Make sure all the functions have documentation
* Show that all the tests are passing
* Modularize! Make functions, have multiple scripts, write a package. This will make it easier to walk through.

During:

* Take notes in the code when your reviewers give feedback, or ask one of the other people involved in the review to take notes for you.
		
After:

* Ask for clarification, especially if you're new to the project or software you're using. More experienced programmers know what they're doing, but they may be unaware of your confidence in a language/project
* Once you've incorporated the feedback, make sure to ask someone to review the changes

### Automatic Code Review {-}

There are a number of good automatic code review tools available to developers. Most of them are free to use for open-source software, but require a membership for private repositories.

Connect your source code to these automatted code review softwares and let them analyze potential errors, inefficiencies, and style. Using an automatted code review software can also help you discover weaknesses in your coding style and when code can be improved.

* [Codacy](https://www.codacy.com/)
* [Codebeat](https://codebeat.co/)
* [SonarQube](https://www.sonarqube.org/)

One large limitation of most (all?) automatted code review software is that it's normally only available for more traditional development softwares. But if you're using a development software, be sure to utilize an automatted code review software. For statistical softwares we're out of luck.

Note, use of such software should not replace the traditional code-review process, especially for data science pipelines which often rely on very specific logic when creating new variables and running models, but it is a quick way to start developing high-quality code.
