## Introduction 

Python is primary used for web testing, pipelining, data management, data science, and visualization.

### Installation {-}

1. Download [Python 3.7.0](https://www.anaconda.com/distribution/) from Anaconda
2. Open Bash and check that Python is saved to the AppData folder
	a. `where python` should return something like `C:\Users\jh111\AppData\Local\Continuum\anaconda3\python.exe`
	b. `where pip` should return something like `C:\Users\jh111\AppData\Local\Continuum\anaconda3\Scripts\pip.exe`
3. If either of these throw an error, like "could not find files...", python and pip need to be added to the PATH environment variable

#### Anaconda Background {-}

We use the Anaconda distribution of python. There are several advantages to using Anaconda over base python, including:

* An Anaconda installation comes with pre-built binaries for many popular packages, including several that we use frequently (numpy, pandas). Installing some of these (e.g. numpy) without Anaconda is very tricky and requires administrator permissions.
* Anaconda comes with very nice environment management tools, which not only allow you to manage your package dependencies per-project, but also your python version. 