### Code Style {-}

#### Style Guides {-}

* [Google Style Guide](https://google.github.io/styleguide/Rguide.xml)
* [Hadley Style Guide](http://adv-r.had.co.nz/Style.html)^[This is based off of the Google Style Guide]

#### General Rules {-}

* Variable names and function names should be lowercase or camel case (be consistent)
* Avoid using names of existing functions/variables

##### Spacing {-}

* Put spaces around all infix operators (=, +, -, <-, etc.)
* ALWAYS put a space after a comma, and never before
* Put a space before left parentheses, except in a function call

##### Curly Braces {-}

* Opening curly brace `{` NEVER goes on its own line, but should always be followed by a new line
* ALWAYS indent code inside curly braces
* Closing curly brace `}` always goes on its own line, unless followed by an `else`

##### Line Length {-}

* Roughly 80 - 90 characters per line

##### Indentation {-}

* ALWAYS use two spaces
* NEVER mix tabs/spaces

##### Assignment {-}

* ALWAYS `<-` not `=`

##### Comments {-}
 
* Comments should begin with `# `
* Comments should explain the why not the what
* Comments that are too lengthy indicate a function should probably be used to break up the code chunk

#### Styling Packages {-}

##### formatR {-}

Automatically formats and spaces code for more human-readability. 

```
library(formatR)
formatR::tidy_dir("R")
```

##### styler {-}

Goal is to provide non-invasive pretty-printing of R source code while adhering to the tidyverse formatting rules.

```
library(styler)
ugly_code <- "a=function( x){1+1}
style_text(ugly_code)

# style_file()
# style_dir()
# style_pkg()
```

##### lintr {-}

Warns you about styling errors and potential problems.

```
library(lintr)
lintr::lint(test.R)
```
