### Debugging {-}

R offers a number of useful built-in functions for debugging, and user-contributed packages are also available to provide additional functionality. The simplest method is to insert commands into your code to print diagnostic"check points" during its execution, using functions such as `cat()`, `print()`, or `sink()`.

R also has a more sophisticated debugging system, which is supported by a GUI in the RStudio IDE. The most direct way to mark a function for debugging is to use `debug(functionname)`. When this function is called, normal execution will be suspended, and you will enter the `browser` display. Commands within the debugged function can then be executed one at a time, and output can be inspected by the programmer along the way. You can set a function to begin debugging partway through its execution with `setBreakpoint()` or `trace()`. If an error is encountered (whether or not the function was being debugged), the `traceback()` command can be used to view the stack of nestedfunction calls at the time of the most recent error.

We illustrate debugging in RStudio with the following example. Suppose we want to debug the `lm()` function to see how it works inside:

```
debug(lm)                          # mark lm() for debugging
lm(speed ~ dist(data=cars))
```

A few things happen when you execute the debugged `lm()` function:

1. In the **Source** pane, a window called the **Source Viewer** opens. This
contains the code of `lm()`.
2. At the bottom of the **Environment** pane, the current stack of function
calls is listed under **Traceback**.
3. The console enters **Browser** mode. In browser mode, a set of buttons appears
along the top of the console (including **Next**, **Continue**, **Stop**, and two
arrow buttons), and the console prompt becomes `Browse[2]>`.

The current location in `lm()` is indicated by the green arrow on the left side of the Source Viewer. In the above figure, the green arrow is on line 4, after the function declaration, but before any of the commands within the function have been executed. This means that all the variables that were entered (or defaulted) in the function call are available. We can enter commands at the command prompt as usual, and they will be executed in the environment of the function:

The commands of the `lm()` function are executed by clicking the button, by typing `n`+Enter, or by pressing Enter in the console. Any of these actions will execute the next command in the `lm()` code, and advance the green arrow in the Source Viewer to the next command. The other control options are:

At any point in executing the `lm()` code, you can run your own commands to look at the contents of an object created within `lm()`, for example, or check objects for errors. When you are finished debugging, exit debugging mode and then run `undebug(lm)`, so the function can be used normally without debugging.

More information on debugging in RStudio can be found [here](https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio), or in the chapter on
[debugging](http://adv-r.had.co.nz/Exceptions-Debugging.html) in the Advanced R book. External packages such as `debug` and `edtdbg` contain alternative debugging interfaces, which are not described here.
